PUSHC
NEWCHARMAP cheats
    CHARMAP " ", $DF
    CHARMAP "!", $DE
    CHARMAP "\"", $DD
    CHARMAP "#", $DC
    CHARMAP "$", $DB
    CHARMAP "%", $DA
    CHARMAP "&", $D9
    CHARMAP "'", $D8
    CHARMAP "(", $D7
    CHARMAP ")", $D6
    CHARMAP "*", $D5
    CHARMAP "+", $D4
    CHARMAP ",", $D3
    CHARMAP "-", $D2
    CHARMAP ".", $D1
    CHARMAP "/", $D0

    CHARMAP "0", $CF
    CHARMAP "1", $CE
    CHARMAP "2", $CD
    CHARMAP "3", $CC
    CHARMAP "4", $CB
    CHARMAP "5", $CA
    CHARMAP "6", $C9
    CHARMAP "7", $C8
    CHARMAP "8", $C7
    CHARMAP "9", $C6
    CHARMAP ":", $C5
    CHARMAP ";", $C4
    CHARMAP "<", $C3
    CHARMAP "=", $C2
    CHARMAP ">", $C1
    CHARMAP "?", $C0

    CHARMAP "@", $BF
    CHARMAP "A", $BE
    CHARMAP "B", $BD
    CHARMAP "C", $BC
    CHARMAP "D", $BB
    CHARMAP "E", $BA
    CHARMAP "F", $B9
    CHARMAP "G", $B8
    CHARMAP "H", $B7
    CHARMAP "I", $B6
    CHARMAP "J", $B5
    CHARMAP "K", $B4
    CHARMAP "L", $B3
    CHARMAP "M", $B2
    CHARMAP "N", $B1
    CHARMAP "O", $B0

    CHARMAP "P", $AF
    CHARMAP "Q", $AE
    CHARMAP "R", $AD
    CHARMAP "S", $AC
    CHARMAP "T", $AB
    CHARMAP "U", $AA
    CHARMAP "V", $A9
    CHARMAP "W", $A8
    CHARMAP "X", $A7
    CHARMAP "Y", $A6
    CHARMAP "Z", $A5
    CHARMAP "[", $A4
    CHARMAP "\\", $A3
    CHARMAP "]", $A2
    CHARMAP "^", $A1
    CHARMAP "_", $A0

    CHARMAP "`", $9F
    CHARMAP "a", $9E
    CHARMAP "b", $9D
    CHARMAP "c", $9C
    CHARMAP "d", $9B
    CHARMAP "e", $9A
    CHARMAP "f", $99
    CHARMAP "g", $98
    CHARMAP "h", $97
    CHARMAP "i", $96
    CHARMAP "j", $95
    CHARMAP "k", $94
    CHARMAP "l", $93
    CHARMAP "m", $92
    CHARMAP "n", $91
    CHARMAP "o", $90

    CHARMAP "p", $8F
    CHARMAP "q", $8E
    CHARMAP "r", $8D
    CHARMAP "s", $8C
    CHARMAP "t", $8B
    CHARMAP "u", $8A
    CHARMAP "v", $89
    CHARMAP "w", $88
    CHARMAP "x", $87
    CHARMAP "y", $86
    CHARMAP "z", $85
    CHARMAP "\{", $84
    CHARMAP "|", $83
    CHARMAP "\}", $82
    CHARMAP "~", $81
POPC
